site_author: ntno
site_name: ntno
site_description: ntno\'s personal site
site_url: http://ntno.net
repo_url: https://github.com/ntno/ntno.net/
theme:
    name: material 
    pallette: 
      primary: 'yellow'
      accent: 'light blue'
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - python
nav:
  - Home: index.md
  - Contact: contact.md
  - FAQ: faq.md

 
