site_name: ntno
repo_url: https://github.com/ntno/ntno.net
edit_uri: edit/main/docs/
site_url: http://ntno.net/
copyright: Copyright 2021-2025 Natan Organick, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Resume: 'resume.md'
    - Projects: 'projects.md'
    - Software: 
      - Index: 'software/index.md' 
      - 'Open Source': 'software/open-source.md'
      - '2023 MkDocs Terminal Theme': 'software/terminal-theme.md'
      - '2021 Cryptography Puzzle': 'software/puzzle.md'
      - '2019 Gifcam': 'software/gifcam.md'
    - Electronics:
      - Index: 'electronics/index.md'
      - '2017-2019 HopperBot': 'electronics/hopper-bot.md'
      - '2019 Skating Vest': 'electronics/led-vest.md'
      - '2018 Brake Light Backpack': 'electronics/led-backpack.md'
    - Wood:
      - Index: 'wood/index.md'
      - '2024 Jewelry Bowl': 'wood/bowl.md'
      - '2020 Laundry Cabinet': 'wood/cabinet.md'
      - '2018 Storage Chest': 'wood/chest.md'
      - '2018 Cutting Boards': 'wood/cutting-boards.md'
    - Textiles:
      - Index: 'textiles/index.md'
      - '2022 Quilt-99': 'textiles/quilt-99.md'
      - '2020 Embroidered Works': 'textiles/embroidered-works.md'
      - '2020 Upcycled Umbrella': 'textiles/pride.md'
      - '2020 Covid-19 Masks': 'textiles/masks.md'
      - 'Selected Knits' : 'textiles/knits.md'
    - Research:
      - Index: 'research/index.md'
      - '2014 SMS Integrated Apps': 'research/2014-sms-and-web-based-apps.md'
      - '2013 Ego Syntonic Learning': 'research/2013-ego-syntonic-learning.md'

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  
plugins:
  - md-to-html
  - git-revision-date

extra_css: 
  - overrides/css/ntno.css

theme:
  name: terminal
  custom_dir: theme_overrides
  # palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
    - revision.history
  static_templates:
    - 404.html

watch:
  - theme_overrides/
  - docs/overrides/
