site_name: ntno
repo_url: https://github.com/ntno/ntno.net
edit_uri: edit/main/docs/
site_url: https://ntno.github.io/ntno.net/
copyright: © Natan Organick 2021, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Resume: 'resume.md'
    - Projects: 'projects.md'
    - 'Projects by Media':
      - Research:
        - '2013 Ego Syntonic Learning': 'research/2013-ego-syntonic-learning.md'
        - '2015 SMS Integrated Apps': 'research/2015-sms-and-web-based-apps.md'
      - Electronics:
        - '2017-2019 HopperBot': 'electronics/hopper-bot.md'
        - '2018 Brake Light Backpack': 'electronics/led-backpack.md'
        - '2019 Gifcam': 'electronics/gifcam.md'
        - '2019 Skating Vest': 'electronics/led-vest.md'
      - 'Software': 'software.md'
      - Wood:
        - '2018 Cutting Boards': 'wood/cutting-boards.md'
        - '2018 Storage Chest': 'wood/chest.md'
        - '2020 Laundry Cabinet': 'wood/cabinet.md'
      - Textiles:
        - '2020 Covid-19 Masks': 'textiles/masks.md'
        - '2020 Upcycled Umbrella': 'textiles/pride.md'
        - '2020 Embroidered Works': 'textiles/embroidered-works.md'

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: "#"
  - attr_list

plugins:
  - search
  - git-revision-date

theme:
    name: null
    custom_dir: 'custom_theme/'
    favicon: img/favicon.ico
