site_name: ntno
repo_url: https://github.com/ntno/ntno.net
edit_uri: edit/main/docs/
site_url: https://ntno.github.io/docs/
copyright: © Natan Organick 2021, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - Projects: 'projects.md'
    - Textiles:
      - 'Embroidery': './textiles/embroidery.md'
      - 'Pride': './textiles/pride.md'
    - Wood:
      - 'Cabinet': './wood/cabinet.md'
      - 'Chest': './wood/chest.md'
      - 'Cutting Boards': './wood/cutting-boards.md'
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - meta
  - toc:
      permalink: "#"

theme:
    name: null
    custom_dir: 'custom_theme/'
    favicon: img/favicon.ico
