site_name: ntno
repo_url: https://github.com/ntno/ntno.net
edit_uri: edit/main/docs/
site_url: https://ntno.github.io/ntno.net/
copyright: © Natan Organick 2021, All rights reserved
site_author: ntno

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Resume: 'resume.md'
    - Projects: 'projects.md'
    - 'Projects by Media':
      - Research:
        - '2013 Ego Syntonic Learning': 'research/2013-ego-syntonic-learning.md'
        - '2015 SMS & Web-based Apps': 'research/2015-sms-and-web-based-apps.md'
      - Electronics:
        - 'HopperBot': 'electronics/hopper-bot.md'
        - 'Brake Light Backpack': 'electronics/led-backpack.md'
      - 'Open Source': 'software.md'
      - Textiles:
        - 'Embroidery': 'textiles/embroidery.md'
        - 'Pride': 'textiles/pride.md'
      - Wood:
        - 'Cabinet': 'wood/cabinet.md'
        - 'Chest': 'wood/chest.md'
        - 'Cutting Boards': 'wood/cutting-boards.md'



markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: "#"
  - attr_list

plugins:
  - search
  - git-revision-date

theme:
    name: null
    custom_dir: 'custom_theme/'
    favicon: img/favicon.ico
