# Simple workflow for building mkdocs site 
name: Build MkDocs Site

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Buildenv
        uses: ntno/setup-buildenv@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Download Image Bundle
        run: |
          make get-image-bundle download-directory="$RUNNER_TEMP/"
      - name: Build Site
        run: |
          source ./scripts/build.sh prod us-east-2
      - name: Archive Site
        run: |
          make bundle input-directory="./site" output-directory="./" bundle-filename="docs-site.tar" manifest-filename="manifest.txt"
          make upload-docs-artifact file="./docs-site.tar" version="${{ github.sha }}"
          make upload-docs-artifact file="./manifest.txt" version="${{ github.sha }}"
      - name: Save GIT_SHA
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./github_sha
          echo "build-sha=$GIT_SHA" > ./github_sha/github_sha_from_build
      - uses: actions/upload-artifact@v3
        with:
          name: github_sha_from_build
          path: ./github_sha/
