# Simple workflow for building mkdocs site 
name: Build MkDocs Site

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Buildenv
        uses: ntno/setup-buildenv@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Download Image Bundle
        run: |
          make get-image-bundle download-path="$RUNNER_TEMP/img-artifact.tar"
      - name: Build Site
        run: |
          source ./scripts/build.sh prod us-east-2
      - name: Archive Site
        run: |
          make bundle input-path="./site" version="${{ github.sha }}"
          make upload-docs-artifact input-path="./${{ github.sha }}.tar" version="${{ github.sha }}"
        
      # - name: Archive artifact
      #   shell: sh
      #   env:
      #     INPUT_PATH: ./site
      #   run: |
      #     chmod -c -R +rX "$INPUT_PATH" | while read line; do
      #       echo "::warning title=Invalid file permissions automatically fixed::$line"
      #     done
      #     tar \
      #       --dereference --hard-dereference \
      #       --directory "$INPUT_PATH" \
      #       -cvf "$RUNNER_TEMP/artifact.tar" \
      #       --exclude=.git \
      #       --exclude=.github \
      #       .