name: Close Pull Request

# only trigger on pull request closed/merged events
on:
  pull_request:
    types: [ closed, merged ]

jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit
  destroy-pr-environment:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Destroy PR Environment
        run: |
          export TEMP_STACK_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
          export TEMP_BUCKET_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
          
          echo "shutting down environment for PR #${{ github.event.number }}"
          
          echo "forcing non-empty bucket delete: s3://${TEMP_BUCKET_NAME}"
          aws s3 rb "s3://${TEMP_BUCKET_NAME}" --force  

          echo "deleting cloudformation stack: ${TEMP_STACK_NAME}"
          aws cloudformation delete-stack --stack-name "${TEMP_STACK_NAME}"