# Sets Metadata for workflow(s)
name: Metadata

on: 
  push:
  pull_request:
    types: [opened, reopened, closed]
  workflow_dispatch:
  workflow_call:
jobs:
  set-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ntno/ntno.net
          tags: |
            type=ref,event=pr
            type=sha
      - name: Inspect Metadata
        run: |
          echo "GITHUB_EVENT={{ github.event }}"
          echo "GITHUB_EVENT_NAME={{ github.event_name }}"
          echo BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          echo VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          echo REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
