# Sets Metadata for workflow(s)
name: Metadata

on: [push, workflow_dispatch]

jobs:
  set-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ntno/ntno.net
      - name: Inspect Metadata
        run: |
          echo BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          echo VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          echo REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
