# Sets Metadata for workflow(s)
name: Metadata

on: 
  push:
  pull_request:
    types: [opened, reopened, closed]
  workflow_dispatch:
  workflow_call:
 
  # workflow_call:
  #   # Map the workflow outputs to job outputs
  #   outputs:
  #     firstword:
  #       description: "The first output string"
  #       value: ${{ jobs.example_job.outputs.output1 }}
  #     secondword:
  #       description: "The second output string"
  #       value: ${{ jobs.example_job.outputs.output2 }}

# jobs:
#   example_job:
#     name: Generate output
#     runs-on: ubuntu-latest

#     steps:
#       - id: step1
#         run: echo "firstword=hello" >> $GITHUB_OUTPUT
#       - id: step2
#         run: echo "secondword=world" >> $GITHUB_OUTPUT
jobs:
  set-metadata:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      event-name: ${{ steps.set-event-name.outputs.event-name }}
      build-tag: ${{ steps.set-build-tag.outputs.build-tag }}
      revision-sha: ${{ steps.set-revision-sha.outputs.revision-sha }}
    steps:
      - name: Generate Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ntno/ntno.net
          tags: |
            type=ref,event=pr
            type=sha
      - id: set-event-name
        run: echo "event-name=${{ github.event_name }}" >> $GITHUB_OUTPUT
      - id: set-build-tag
        run: echo "build-tag=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT
      - id: set-revision-sha
        run: echo "revision-sha=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}" >> $GITHUB_OUTPUT
      - id: stash-event-payload
        run: |
          mkdir -p ./details
          cat ${{ github.event_path }} > ./details/payload.json
      - uses: actions/upload-artifact@v3
        with:
          name: payload.json
          path: ./details/

  # job1:
  #     runs-on: ubuntu-latest
  #     # Map a step output to a job output
  #     outputs:
  #       output1: ${{ steps.step1.outputs.test }}
  #       output2: ${{ steps.step2.outputs.test }}
  #     steps:
  #       - id: step1
  #         run: echo "test=hello" >> $GITHUB_OUTPUT
  #       - id: step2
  #         run: echo "test=world" >> $GITHUB_OUTPUT
  #   job2:
  #     runs-on: ubuntu-latest
  #     needs: job1
  #     steps:
  #       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

