name: Open Pull Request

# only trigger on pull request open or reopen events
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  set-metadata:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit
  create-pr-environment:
    needs: [set-metadata]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo creating new environment for PR #${{ github.event.number }}
      