name: Open Pull Request

# only trigger on pull request open or reopen events
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit
  create-pr-environment:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2
      # - name: Create PR Environment
      #   id: create-pr-env
      #   working-directory: ./scripts/pr-env
      #   run: |
      #     echo "creating new environment for PR #${{ github.event.number }}"
      #     export TEMP_STACK_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
      #     export TEMP_BUCKET_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
      #     aws cloudformation create-stack \
      #               --template-body file://s3-website.yml \
      #               --stack-name ${TEMP_BUCKET_NAME}  \
      #               --parameters  ParameterKey=BucketName,ParameterValue=${TEMP_BUCKET_NAME} \
      #               --on-failure DO_NOTHING \
      #               --capabilities CAPABILITY_NAMED_IAM
      #     aws cloudformation wait stack-create-complete --stack-name ${TEMP_BUCKET_NAME} 
      #     aws s3 cp --sse AES256 --acl public-read index.html s3://${TEMP_BUCKET_NAME}/
      #     aws s3 cp --sse AES256 --acl public-read error.html s3://${TEMP_BUCKET_NAME}/
      - name: Comment on PR with Environment URL
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          export TEMP_BUCKET_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
          export URL="http://${TEMP_BUCKET_NAME}.s3-website.us-east-2.amazonaws.com"
          export MESSAGE="please review changes at ${URL}"
          gh pr comment ${{ github.event.number }} --body ${MESSAGE}
          echo "::notice $URL"

