name: Open Pull Request

# only trigger on pull request open or reopen events
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit
  create-pr-environment:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Create PR Environment
        working-directory: ./scripts
        run: |
          echo "creating new environment for PR #${{ github.event.number }}"
          export TEMP_BUCKET_NAME="${{ secrets.CI_USER }}-${{ needs.call-metadata-workflow.outputs.build-tag }}"
          aws cloudformation create-stack \
                    --template-body file://s3-website.yml \
                    --stack-name ${TEMP_BUCKET_NAME}  \
                    --parameters  ParameterKey=BucketName,ParameterValue=${TEMP_BUCKET_NAME} 