# Simple workflow for releasing mkdocs site 
name: Release

on:
  workflow_dispatch:
  release:
  
jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit 
  build-release:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    environment: ci
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Buildenv
        uses: ntno/setup-buildenv@v1     
      - name: Set Env Vars
        id: set-env-vars
        run: |
          if [[ "${{ needs.call-metadata-workflow.outputs.release-is-prerelease }}" == "true" ]]; then
              echo "Release is marked as prerelease, skipping site archive upload..."
              echo "archive-build=false" >> $GITHUB_ENV
          else
              echo "archive-build=true" >> $GITHUB_ENV
          fi
      - name: Build Release
        uses: ntno/build-mkdocs-composite-action@add-make-vars
        with:
          archive-enabled: ${{ env.archive-build }}
          version: ${{ needs.call-metadata-workflow.outputs.release-name }}
          env-name: prod
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Report Result
        run: |
          export MESSAGE="Release ${{ needs.call-metadata-workflow.outputs.release-name }} built with ${{ needs.call-metadata-workflow.outputs.build-tag }}"
          echo "::notice title=Release Built::$MESSAGE"
  deploy-release:
    needs: [call-metadata-workflow, build-release]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Buildenv
        uses: ntno/setup-buildenv@v1
      - name: Set Env Vars
        id: set-env-vars
        run: |
          if [[ "${{ needs.call-metadata-workflow.outputs.release-is-prerelease }}" == "true" ]]; then
              echo "Release is marked as prerelease, running deploy as dry-run..."
              echo "deploy-flags=DRY_RUN=1" >> $GITHUB_ENV
          else
              echo "deploy-flags=DRY_RUN=0" >> $GITHUB_ENV
          fi   
      - name: Deploy Release
        id: deploy-mkdocs
        uses: ntno/deploy-mkdocs-composite-action@add-dry-run-option
        with:         
          version: ${{ needs.call-metadata-workflow.outputs.release-name }}
          env-name: prod
          s3-bucket: ntno.net
          aws-region: us-east-2
          make-vars-for-deploy-target: ${{ env.deploy-flags }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Report Result
        run: |
          export MESSAGE="Release ${{ needs.call-metadata-workflow.outputs.release-name }} deployed to http://ntno.net.s3-website.us-east-2.amazonaws.com with ${{ needs.call-metadata-workflow.outputs.build-tag }}"        
          echo "::notice title=Release Deployed::$MESSAGE"
      
