# Sets Custom OIDC Subject Claims for repository
# see https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
name: Set Custom OIDC Claims

on: 
  workflow_dispatch:

jobs:
  set-custom-oidc-claims:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: customize-oidc-claims
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/oidc/customization/sub \
            -d '{"use_default":false,"include_claim_keys":["repo","context", "environment"]}'
      - name: report-repository-oidc-subject-claim
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/oidc/customization/sub