# Sets Custom OIDC Claims for repository
name: Set Custom OIDC Claims

on: 
  workflow_dispatch:

jobs:
  set-custom-oidc-claims:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: customize-oidc-claims
        working-directory: ./.github/workflows
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh api /repos/${{ github.repository_owner }}/${{ github.repository }}/actions/oidc/customization/sub -H "Accept: application/vnd.github+json" -X PUT --input claims.json
      
