# Simple workflow for testing mkdocs site 
name: Test Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]
  
jobs:
  call-metadata-workflow:
    uses: ./.github/workflows/meta.yml 
    secrets: inherit 
  build-pr:
    needs: [call-metadata-workflow]
    runs-on: ubuntu-latest
    environment: ci
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build PR
        uses: ntno/build-mkdocs-composite-action@generalize
        with:
          archive-enabled: true
          version: ${{ needs.call-metadata-workflow.outputs.build-tag }}
          env-name: prod
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Report Result
        run: |
          echo "PR #${{ needs.call-metadata-workflow.outputs.pr-number }} built with version=${{ needs.call-metadata-workflow.outputs.build-tag }}"
  deploy-pr:
    runs-on: ubuntu-latest
    needs: [call-metadata-workflow, build-pr]
    steps:
      - name: Install Buildenv
        uses: ntno/setup-buildenv@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Download Archived Site
        run: |
          export BUILD_TAG="${{ needs.call-metadata-workflow.outputs.build-tag }}"
          make download-docs-artifact version="${BUILD_TAG}" file="docs-site.tar" output-path="."
      - name: Deploy Archived Site 
        run: |
          mkdir -p site
          tar \
            --directory "./site/" \
            -xf ./docs-site.tar 
          
          export TEMP_BUCKET_NAME="${{ needs.call-metadata-workflow.outputs.pr-env }}"
          aws s3 sync --no-progress --sse AES256 --acl public-read ./site/ s3://${TEMP_BUCKET_NAME}/

